### PR TITLE
Mercury project version (in progress)

### PR DESCRIPTION
**Pull request by dav1248**
**Preliminary version of simple-spectro eagle file for the purpose of the Mercury Project in Univalle, Cali.** 

Changes
* adding of voltage inverter TPS60400 for UV LED
* adding of digital potentiometer MCP4452, liberated pins **A0/A1** for GPRS communication
* adding of I2C (RJ12) connector
* adding of (temporary) connector for LED and light to freq. converter for Bioreactor
* Replacing of **SCL/SDA** by **A2/A4** on MC pins to free SCL/SDA for I2C slave connection
* adding of SIM800L module (linked VBAT1 with pin of SIM800L, moved screen brightness adjuster and its caps)

Remarques:
* nets A0/A1 not routed
* nets D12/HWB not routed

Questions
* Y a-t-il besoin de libérer un pin supplémentaire sur le MC pour le reset du module GPRS?
* Peut-on utiliser des pins Analog (A0, A1)  comme software serial comm. avec le module GPRS?
* Est-ce OK de connecter le 5V de la connection I2C slave à VUSB?
* A quoi connecter GND1 et GND 2 (toujours pour I2C)?
* Quelles valeurs pour condensateurs de l'inverseur de voltage?

### CODE REVIEW

**Comment by lpatiny** [comment]
sim800L:
* A0 and A1 should be ok for software serial
* RST if there is a pin available would be nice. Othewise should be forced either to VCC or GND depending specifications
* 5V I2 should go through a Schottky like for the Vusb
* I2C GND 1 and 2 should go to GND
* capacity for inverter should be the one from the specifications (1u)

**Comment by lpatiny** [comment]
It seems to me it will be easier to replace the quad digital pot by MCP4728. This component is internally protected and allows to give up to 10mA. Not obvious for the quad pot.

**Comment by lpatiny** [comment]
* When connecting to GND just create a via. No need to make long traces and many of them (also existing one) should be shortened.
* On the front side please try to create a VCC plane in order also to reduce the number of traces
* Please also try to add https://github.com/Hackuarium/simple-spectro/issues/78 It would be connected like the blue led of the RGB but connected to -3.3V. It should have its own resistor (default 1k)
* Add a resistor to the UV led, default 100 Ohms

**Comment by lpatiny** [comment]
Could move all those components higher to have more room for sim800l

image

**Comment by dav1248** [comment]
Question pour le connecteur bioréacteur :
Actuellement, il y a 7 fils qui partent de la carte pour le plongeur :
-	2 pour la LED UV (dont GND)
-	2 pour la LED RGB (rouge + GND)
-	3 pour le capteur (GND + D12 + HWB)
Faut-il changer cela du coup ?

**Comment by lpatiny** [comment]
Il faut leur demander mais oui je le changerais. Il faut qu'un GND de toutes façons. La LED RGB externe pourrait avoir ses propres résistances éventuellement ce qui donnerait un peu plus de flexibilité

**Comment by dav1248** [comment]
first correction

* RST pin of SIM800L connected to VCC following specifications
* Added a Schottky for 5V I2C
* Replaced digipot by MCP4728
* Created a VCC plane on back (blue) side
* added #78
* added default 100ohm resistor to UV led
* added bioreactor RJ12 connector

Info: SIM800L is on the same side as the LCD

**Pull request merged**
